### ISSUE TITLE
FancyboxHelper::output()

### ISSUE THREAD

**Issue by arc3x** [destinydriven/CakePHP-Fancybox-Plugin#1]
I don't see anything about this on the internet so i'm not sure if its just a local problem / version compatibility issue.

My error:
Strict (2048): Declaration of FancyboxHelper::output() should be compatible with Helper::output($str) [APP\Plugin\Fancybox\View\Helper\FancyboxHelper.php, line 152]

My solution (might as well merge because it doesn't hurt):
FancyBoxHelper.php line 71 =>
public function output($str = null) {

**Comment by destinydriven** [comment]
@arco000 Thanks :+1:
